### ISSUE TITLE
Release Binaries Not Attached

### ISSUE THREAD

**Issue by osterman** [cloudposse/tfenv#2]
## what
* Release binaries not attached

## why
* Maybe envs for pipeline not setup

**Comment by osterman** [comment]
@aknysh can you help me finish the setup? =) you're the master

**Comment by aknysh** [comment]
@osterman 
this is fixed https://github.com/cloudposse/tfenv/releases/tag/0.1.0
Travis was missing GitHub API key and Docker Hub credentials

**Comment by osterman** [comment]
thanks!
